# Usign the Clean Blog theme

title: Homepage of Yassine Yousfi
author: Yassine Yousfi
email: yyousfi1@binghamton.edu
description: Homepage of Yassine Yousfi
baseurl: ""
twitter_username: yassineyousfi_
github_username: YassineYousfi
linkedin_username: yassine-yousfi-
email: yyousfi1@binghamton.edu

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]
exclude: [vendor]

scholar:
  style: mla
  source: ./_bibliography


target-blank:
    css_class: ext-link

name: Yassine Yousfi, recent works
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-scholar
  - jekyll-target-blank

